package com.springboot.appmapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.springboot.appmodel.Customers;
import com.springboot.appmodel.CustomersExample.Criteria;
import com.springboot.appmodel.CustomersExample.Criterion;
import com.springboot.appmodel.CustomersExample;
import java.util.List;
import java.util.Map;

public class CustomersSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Tue Dec 22 23:50:08 CST 2020
     */
    public String countByExample(CustomersExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("customers");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Tue Dec 22 23:50:08 CST 2020
     */
    public String deleteByExample(CustomersExample example) {
        BEGIN();
        DELETE_FROM("customers");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Tue Dec 22 23:50:08 CST 2020
     */
    public String insertSelective(Customers record) {
        BEGIN();
        INSERT_INTO("customers");
        
        if (record.getCustId() != null) {
            VALUES("cust_id", "#{custId,jdbcType=INTEGER}");
        }
        
        if (record.getCustName() != null) {
            VALUES("cust_name", "#{custName,jdbcType=CHAR}");
        }
        
        if (record.getCustAddress() != null) {
            VALUES("cust_address", "#{custAddress,jdbcType=CHAR}");
        }
        
        if (record.getCustCity() != null) {
            VALUES("cust_city", "#{custCity,jdbcType=CHAR}");
        }
        
        if (record.getCustState() != null) {
            VALUES("cust_state", "#{custState,jdbcType=CHAR}");
        }
        
        if (record.getCustZip() != null) {
            VALUES("cust_zip", "#{custZip,jdbcType=CHAR}");
        }
        
        if (record.getCustCountry() != null) {
            VALUES("cust_country", "#{custCountry,jdbcType=CHAR}");
        }
        
        if (record.getCustContact() != null) {
            VALUES("cust_contact", "#{custContact,jdbcType=CHAR}");
        }
        
        if (record.getCustEmail() != null) {
            VALUES("cust_email", "#{custEmail,jdbcType=CHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Tue Dec 22 23:50:08 CST 2020
     */
    public String selectByExample(CustomersExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("cust_id");
        } else {
            SELECT("cust_id");
        }
        SELECT("cust_name");
        SELECT("cust_address");
        SELECT("cust_city");
        SELECT("cust_state");
        SELECT("cust_zip");
        SELECT("cust_country");
        SELECT("cust_contact");
        SELECT("cust_email");
        FROM("customers");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Tue Dec 22 23:50:08 CST 2020
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Customers record = (Customers) parameter.get("record");
        CustomersExample example = (CustomersExample) parameter.get("example");
        
        BEGIN();
        UPDATE("customers");
        
        if (record.getCustId() != null) {
            SET("cust_id = #{record.custId,jdbcType=INTEGER}");
        }
        
        if (record.getCustName() != null) {
            SET("cust_name = #{record.custName,jdbcType=CHAR}");
        }
        
        if (record.getCustAddress() != null) {
            SET("cust_address = #{record.custAddress,jdbcType=CHAR}");
        }
        
        if (record.getCustCity() != null) {
            SET("cust_city = #{record.custCity,jdbcType=CHAR}");
        }
        
        if (record.getCustState() != null) {
            SET("cust_state = #{record.custState,jdbcType=CHAR}");
        }
        
        if (record.getCustZip() != null) {
            SET("cust_zip = #{record.custZip,jdbcType=CHAR}");
        }
        
        if (record.getCustCountry() != null) {
            SET("cust_country = #{record.custCountry,jdbcType=CHAR}");
        }
        
        if (record.getCustContact() != null) {
            SET("cust_contact = #{record.custContact,jdbcType=CHAR}");
        }
        
        if (record.getCustEmail() != null) {
            SET("cust_email = #{record.custEmail,jdbcType=CHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Tue Dec 22 23:50:08 CST 2020
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("customers");
        
        SET("cust_id = #{record.custId,jdbcType=INTEGER}");
        SET("cust_name = #{record.custName,jdbcType=CHAR}");
        SET("cust_address = #{record.custAddress,jdbcType=CHAR}");
        SET("cust_city = #{record.custCity,jdbcType=CHAR}");
        SET("cust_state = #{record.custState,jdbcType=CHAR}");
        SET("cust_zip = #{record.custZip,jdbcType=CHAR}");
        SET("cust_country = #{record.custCountry,jdbcType=CHAR}");
        SET("cust_contact = #{record.custContact,jdbcType=CHAR}");
        SET("cust_email = #{record.custEmail,jdbcType=CHAR}");
        
        CustomersExample example = (CustomersExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Tue Dec 22 23:50:08 CST 2020
     */
    public String updateByPrimaryKeySelective(Customers record) {
        BEGIN();
        UPDATE("customers");
        
        if (record.getCustName() != null) {
            SET("cust_name = #{custName,jdbcType=CHAR}");
        }
        
        if (record.getCustAddress() != null) {
            SET("cust_address = #{custAddress,jdbcType=CHAR}");
        }
        
        if (record.getCustCity() != null) {
            SET("cust_city = #{custCity,jdbcType=CHAR}");
        }
        
        if (record.getCustState() != null) {
            SET("cust_state = #{custState,jdbcType=CHAR}");
        }
        
        if (record.getCustZip() != null) {
            SET("cust_zip = #{custZip,jdbcType=CHAR}");
        }
        
        if (record.getCustCountry() != null) {
            SET("cust_country = #{custCountry,jdbcType=CHAR}");
        }
        
        if (record.getCustContact() != null) {
            SET("cust_contact = #{custContact,jdbcType=CHAR}");
        }
        
        if (record.getCustEmail() != null) {
            SET("cust_email = #{custEmail,jdbcType=CHAR}");
        }
        
        WHERE("cust_id = #{custId,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Tue Dec 22 23:50:08 CST 2020
     */
    protected void applyWhere(CustomersExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}