package com.demo.springboot2demo02.mapper;

import com.demo.springboot2demo02.model.Orders;
import com.demo.springboot2demo02.model.OrdersExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated 2021-02-0600:52:13
     */
    @SelectProvider(type=OrdersSqlProvider.class, method="countByExample")
    long countByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated 2021-02-0600:52:13
     */
    @DeleteProvider(type=OrdersSqlProvider.class, method="deleteByExample")
    int deleteByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated 2021-02-0600:52:13
     */
    @Delete({
        "delete from orders",
        "where order_num = #{orderNum,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer orderNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated 2021-02-0600:52:13
     */
    @Insert({
        "insert into orders (order_num, order_date, ",
        "cust_id)",
        "values (#{orderNum,jdbcType=INTEGER}, #{orderDate,jdbcType=TIMESTAMP}, ",
        "#{custId,jdbcType=INTEGER})"
    })
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated 2021-02-0600:52:13
     */
    @InsertProvider(type=OrdersSqlProvider.class, method="insertSelective")
    int insertSelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated 2021-02-0600:52:13
     */
    @SelectProvider(type=OrdersSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="order_num", property="orderNum", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="order_date", property="orderDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="cust_id", property="custId", jdbcType=JdbcType.INTEGER)
    })
    List<Orders> selectByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated 2021-02-0600:52:13
     */
    @Select({
        "select",
        "order_num, order_date, cust_id",
        "from orders",
        "where order_num = #{orderNum,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="order_num", property="orderNum", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="order_date", property="orderDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="cust_id", property="custId", jdbcType=JdbcType.INTEGER)
    })
    Orders selectByPrimaryKey(Integer orderNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated 2021-02-0600:52:13
     */
    @UpdateProvider(type=OrdersSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Orders record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated 2021-02-0600:52:13
     */
    @UpdateProvider(type=OrdersSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Orders record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated 2021-02-0600:52:13
     */
    @UpdateProvider(type=OrdersSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated 2021-02-0600:52:13
     */
    @Update({
        "update orders",
        "set order_date = #{orderDate,jdbcType=TIMESTAMP},",
          "cust_id = #{custId,jdbcType=INTEGER}",
        "where order_num = #{orderNum,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Orders record);
}