package com.example.springbootshiro.model;

import java.util.Date;

public class Permissions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.id
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.name
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.type
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.url
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.permission
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.parent_id
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.sort
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.external
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    private Byte external;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.available
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    private Byte available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.icon
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.create_time
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.update_time
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.id
     *
     * @return the value of sys_resources.id
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.id
     *
     * @param id the value for sys_resources.id
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.name
     *
     * @return the value of sys_resources.name
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.name
     *
     * @param name the value for sys_resources.name
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.type
     *
     * @return the value of sys_resources.type
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.type
     *
     * @param type the value for sys_resources.type
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.url
     *
     * @return the value of sys_resources.url
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.url
     *
     * @param url the value for sys_resources.url
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.permission
     *
     * @return the value of sys_resources.permission
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.permission
     *
     * @param permission the value for sys_resources.permission
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.parent_id
     *
     * @return the value of sys_resources.parent_id
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.parent_id
     *
     * @param parentId the value for sys_resources.parent_id
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.sort
     *
     * @return the value of sys_resources.sort
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.sort
     *
     * @param sort the value for sys_resources.sort
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.external
     *
     * @return the value of sys_resources.external
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public Byte getExternal() {
        return external;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.external
     *
     * @param external the value for sys_resources.external
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public void setExternal(Byte external) {
        this.external = external;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.available
     *
     * @return the value of sys_resources.available
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public Byte getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.available
     *
     * @param available the value for sys_resources.available
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public void setAvailable(Byte available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.icon
     *
     * @return the value of sys_resources.icon
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.icon
     *
     * @param icon the value for sys_resources.icon
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.create_time
     *
     * @return the value of sys_resources.create_time
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.create_time
     *
     * @param createTime the value for sys_resources.create_time
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.update_time
     *
     * @return the value of sys_resources.update_time
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.update_time
     *
     * @param updateTime the value for sys_resources.update_time
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Permissions other = (Permissions) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getPermission() == null ? other.getPermission() == null : this.getPermission().equals(other.getPermission()))
            && (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
            && (this.getExternal() == null ? other.getExternal() == null : this.getExternal().equals(other.getExternal()))
            && (this.getAvailable() == null ? other.getAvailable() == null : this.getAvailable().equals(other.getAvailable()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getPermission() == null) ? 0 : getPermission().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getExternal() == null) ? 0 : getExternal().hashCode());
        result = prime * result + ((getAvailable() == null) ? 0 : getAvailable().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", url=").append(url);
        sb.append(", permission=").append(permission);
        sb.append(", parentId=").append(parentId);
        sb.append(", sort=").append(sort);
        sb.append(", external=").append(external);
        sb.append(", available=").append(available);
        sb.append(", icon=").append(icon);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}