package com.example.springbootshiro.model;

import java.util.Date;

public class RolePermissions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resources.id
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resources.role_id
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resources.resources_id
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    private Long resourcesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resources.create_time
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resources.update_time
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resources.id
     *
     * @return the value of sys_role_resources.id
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resources.id
     *
     * @param id the value for sys_role_resources.id
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resources.role_id
     *
     * @return the value of sys_role_resources.role_id
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resources.role_id
     *
     * @param roleId the value for sys_role_resources.role_id
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resources.resources_id
     *
     * @return the value of sys_role_resources.resources_id
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public Long getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resources.resources_id
     *
     * @param resourcesId the value for sys_role_resources.resources_id
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public void setResourcesId(Long resourcesId) {
        this.resourcesId = resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resources.create_time
     *
     * @return the value of sys_role_resources.create_time
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resources.create_time
     *
     * @param createTime the value for sys_role_resources.create_time
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resources.update_time
     *
     * @return the value of sys_role_resources.update_time
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resources.update_time
     *
     * @param updateTime the value for sys_role_resources.update_time
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RolePermissions other = (RolePermissions) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getResourcesId() == null ? other.getResourcesId() == null : this.getResourcesId().equals(other.getResourcesId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getResourcesId() == null) ? 0 : getResourcesId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", resourcesId=").append(resourcesId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}