package com.example.springbootshiro.mapper;

import com.example.springbootshiro.model.RolePermissions;
import com.example.springbootshiro.model.RolePermissionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface RolePermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    @SelectProvider(type=RolePermissionsSqlProvider.class, method="countByExample")
    int countByExample(RolePermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    @DeleteProvider(type=RolePermissionsSqlProvider.class, method="deleteByExample")
    int deleteByExample(RolePermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    @Delete({
        "delete from sys_role_resources",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    @Insert({
        "insert into sys_role_resources (id, role_id, ",
        "resources_id, create_time, ",
        "update_time)",
        "values (#{id,jdbcType=BIGINT}, #{roleId,jdbcType=BIGINT}, ",
        "#{resourcesId,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(RolePermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    @InsertProvider(type=RolePermissionsSqlProvider.class, method="insertSelective")
    int insertSelective(RolePermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    @SelectProvider(type=RolePermissionsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="role_id", property="roleId", jdbcType=JdbcType.BIGINT),
        @Result(column="resources_id", property="resourcesId", jdbcType=JdbcType.BIGINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<RolePermissions> selectByExample(RolePermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    @Select({
        "select",
        "id, role_id, resources_id, create_time, update_time",
        "from sys_role_resources",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="role_id", property="roleId", jdbcType=JdbcType.BIGINT),
        @Result(column="resources_id", property="resourcesId", jdbcType=JdbcType.BIGINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    RolePermissions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    @UpdateProvider(type=RolePermissionsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") RolePermissions record, @Param("example") RolePermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    @UpdateProvider(type=RolePermissionsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") RolePermissions record, @Param("example") RolePermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    @UpdateProvider(type=RolePermissionsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(RolePermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resources
     *
     * @mbggenerated Sun Dec 27 16:04:48 CST 2020
     */
    @Update({
        "update sys_role_resources",
        "set role_id = #{roleId,jdbcType=BIGINT},",
          "resources_id = #{resourcesId,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(RolePermissions record);
}