package com.example.demo.basemodel;

public class Customers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.cust_id
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    private Integer custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.cust_name
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.cust_address
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    private String custAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.cust_city
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    private String custCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.cust_state
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    private String custState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.cust_zip
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    private String custZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.cust_country
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    private String custCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.cust_contact
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    private String custContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.cust_email
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    private String custEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.cust_id
     *
     * @return the value of customers.cust_id
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.cust_id
     *
     * @param custId the value for customers.cust_id
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.cust_name
     *
     * @return the value of customers.cust_name
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.cust_name
     *
     * @param custName the value for customers.cust_name
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.cust_address
     *
     * @return the value of customers.cust_address
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public String getCustAddress() {
        return custAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.cust_address
     *
     * @param custAddress the value for customers.cust_address
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public void setCustAddress(String custAddress) {
        this.custAddress = custAddress == null ? null : custAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.cust_city
     *
     * @return the value of customers.cust_city
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public String getCustCity() {
        return custCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.cust_city
     *
     * @param custCity the value for customers.cust_city
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public void setCustCity(String custCity) {
        this.custCity = custCity == null ? null : custCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.cust_state
     *
     * @return the value of customers.cust_state
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public String getCustState() {
        return custState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.cust_state
     *
     * @param custState the value for customers.cust_state
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public void setCustState(String custState) {
        this.custState = custState == null ? null : custState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.cust_zip
     *
     * @return the value of customers.cust_zip
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public String getCustZip() {
        return custZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.cust_zip
     *
     * @param custZip the value for customers.cust_zip
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public void setCustZip(String custZip) {
        this.custZip = custZip == null ? null : custZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.cust_country
     *
     * @return the value of customers.cust_country
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public String getCustCountry() {
        return custCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.cust_country
     *
     * @param custCountry the value for customers.cust_country
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public void setCustCountry(String custCountry) {
        this.custCountry = custCountry == null ? null : custCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.cust_contact
     *
     * @return the value of customers.cust_contact
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public String getCustContact() {
        return custContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.cust_contact
     *
     * @param custContact the value for customers.cust_contact
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public void setCustContact(String custContact) {
        this.custContact = custContact == null ? null : custContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.cust_email
     *
     * @return the value of customers.cust_email
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public String getCustEmail() {
        return custEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.cust_email
     *
     * @param custEmail the value for customers.cust_email
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    public void setCustEmail(String custEmail) {
        this.custEmail = custEmail == null ? null : custEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Customers other = (Customers) that;
        return (this.getCustId() == null ? other.getCustId() == null : this.getCustId().equals(other.getCustId()))
            && (this.getCustName() == null ? other.getCustName() == null : this.getCustName().equals(other.getCustName()))
            && (this.getCustAddress() == null ? other.getCustAddress() == null : this.getCustAddress().equals(other.getCustAddress()))
            && (this.getCustCity() == null ? other.getCustCity() == null : this.getCustCity().equals(other.getCustCity()))
            && (this.getCustState() == null ? other.getCustState() == null : this.getCustState().equals(other.getCustState()))
            && (this.getCustZip() == null ? other.getCustZip() == null : this.getCustZip().equals(other.getCustZip()))
            && (this.getCustCountry() == null ? other.getCustCountry() == null : this.getCustCountry().equals(other.getCustCountry()))
            && (this.getCustContact() == null ? other.getCustContact() == null : this.getCustContact().equals(other.getCustContact()))
            && (this.getCustEmail() == null ? other.getCustEmail() == null : this.getCustEmail().equals(other.getCustEmail()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCustId() == null) ? 0 : getCustId().hashCode());
        result = prime * result + ((getCustName() == null) ? 0 : getCustName().hashCode());
        result = prime * result + ((getCustAddress() == null) ? 0 : getCustAddress().hashCode());
        result = prime * result + ((getCustCity() == null) ? 0 : getCustCity().hashCode());
        result = prime * result + ((getCustState() == null) ? 0 : getCustState().hashCode());
        result = prime * result + ((getCustZip() == null) ? 0 : getCustZip().hashCode());
        result = prime * result + ((getCustCountry() == null) ? 0 : getCustCountry().hashCode());
        result = prime * result + ((getCustContact() == null) ? 0 : getCustContact().hashCode());
        result = prime * result + ((getCustEmail() == null) ? 0 : getCustEmail().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbggenerated Mon Sep 13 10:58:05 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", custId=").append(custId);
        sb.append(", custName=").append(custName);
        sb.append(", custAddress=").append(custAddress);
        sb.append(", custCity=").append(custCity);
        sb.append(", custState=").append(custState);
        sb.append(", custZip=").append(custZip);
        sb.append(", custCountry=").append(custCountry);
        sb.append(", custContact=").append(custContact);
        sb.append(", custEmail=").append(custEmail);
        sb.append("]");
        return sb.toString();
    }
}